---
- name: install Docker
  hosts: all
  become: true
  tasks:
    - name: Install apt-transport-https
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - lsb-release
          - gnupg
        state: latest
        update_cache: true

    - name: Add signing key
      ansible.builtin.apt_key:
        url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
        state: present

    - name: Add repository into sources list
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ ansible_architecture }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
        state: present
        filename: docker
    - name: Installing Docker package
      package:
        name: 
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose
        state: present
    - name: Starting docker service
      service:
        name: "docker"
        state: started
        enabled: yes
    # name: Installing Docker SDK for python3
    #  command: pip3 install docker
    

    - name: Clone a repo with separate git directory 
      ansible.builtin.git:
        repo: https://github.com/AmeraB84/projet_final_devops.git   
        dest: /home/aziza/final     
